# Generated by Django 4.2.27 on 2026-01-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mannequin_image_path",
            field=models.CharField(
                blank=True,
                help_text="Firebase Storage path for mannequin image",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mannequin_image_url",
            field=models.URLField(
                blank=True, help_text="Public download URL for mannequin image", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mannequin_uploaded_at",
            field=models.DateTimeField(
                blank=True, help_text="When the mannequin image was last uploaded", null=True
            ),
        ),
    ]
