# Generated by Django 4.2.27 on 2026-01-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile_mannequin_image_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mannequin_image_url",
            field=models.URLField(
                blank=True,
                help_text="Public download URL for mannequin image",
                max_length=2048,
                null=True,
            ),
        ),
    ]
