# Generated by Django 4.2.27 on 2026-01-06 17:11

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_increase_url_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="WardrobeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("top", "Top"), ("bottom", "Bottom")],
                        db_index=True,
                        help_text="Clothing category: top or bottom",
                        max_length=10,
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Firebase Storage path for the item image", max_length=500
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="Signed download URL for the item image", max_length=2048
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wardrobe_items",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wardrobe Item",
                "verbose_name_plural": "Wardrobe Items",
                "db_table": "wardrobe_items",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["user_profile", "category"], name="wardrobe_it_user_pr_ee58f0_idx"
                    )
                ],
            },
        ),
    ]
